server:
  port: 8080

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
  freemarker:
    suffix: .ftl
